#ifndef LEDCONFIG_H
#define LEDCONFIG_H

#define NOF_SECTORS 320
#define NOF_LEDS 32 //64
#define LED_DATA_SIZE 4
#define POV_FRAME_SIZE (NOF_SECTORS * NOF_LEDS * LED_DATA_SIZE)


#endif // LEDCONFIG_H
